config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :order_items
  resource :carts, only: [:show]
  
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	before_save :set_subtotal

	def subtotal
		order_items.collect {|order_item| order_item.valid? ? (order_item.unit_price*order_item.quantity) : 0}.sum
	end

	private
		def set_subtotal
			self[:subtotal] = subtotal
		end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :product

	before_save :set_unit_price
	before_save :set_total_price

	def unit_price
		if persisted?
			self[:unit_price]
		else
			product.price
		end
	end

	def total_price
		unit_price * quantity
	end

	private

		def set_unit_price
			self[:unit_price] = unit_price
		end

		def set_total_price
			self[:total_price] = quantity * set_unit_price
		end
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :order_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include ApplicationHelper
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
		@order_items = current_order.order_items
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@products = Product.all
  	@order_item = current_order.order_items.new
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

	def create
		@order = current_order
		@order_item = @order.order_items.new(order_item_params)
		@order.save
		session[:order_id] = @order.id
	end

	def update
		@order = current_order
		@order_item = @order.order_items.find(params[:id])
		@order_item.update_attributes(order_item_params)
		@order_items = @order.order_items
	end

	def destroy
		@order = current_order
		@order_item = @order.order_items.find(params[:id])
		@order_item.destroy
		@order_items = @order.order_items
	end

	private
		def order_item_params
			params.require(:order_item).permit(:product_id, :quantity)
		end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  def show
    
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path    
  end

  private
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_order
		if !session[:order_id].nil?
			Order.find(session[:order_id])
		else
			Order.new
		end
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart_item.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
	<ul>
		<% @order_item.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<% if @order_items.size>0 %>
	<% @order_items.each do |item| %>
		<div class="well">
			<div class="row">
				<div class="col-sm-8">
					<h3><%= item.product.name %></h3>
				</div>
				<div class="col-sm-4">
					<div class="pull-right">
					<%= form_for(item, remote: true) do |f| %>
						<%= f.hidden_field :product_id, value: item.product.id %>
						<h5><%= item.product.price %></h5>
						<div class="form-group">
							<%= f.text_field :quantity, value: item.quantity.to_i, min: 1, class: 'form-control' %>
						</div>
						<div class="btn-group">
							<%= f.submit "Update Quantity", class: 'btn btn-primary' %>
							<%= link_to "Delete", item, method: :delete, remote: true, class: 'btn btn-danger'  %>
						</div>
						<span>Total Price: <%= item.total_price %></span>
					<% end %>
					</div>
				</div>
			</div>
		</div>
	<% end %>
<% else %>
	
<% end %>

app/views/carts/show.html.erb
<div class="cart_item">
	<%= render "carts/cart_item" %>
</div>2

app/views/home/index.html.erb
<%= link_to "Create new list of products", products_path %>

<h1>Products for sale</h1>

<% @products.each do |product| %>
	<div class="well">
		<div class="row">
			<div class="col-sm-8">
				<h3><%= product.name %></h3>
			</div>
			<div class="col-sm-4">
				<div class="pull-right">
				<%= form_for(@order_item, remote: true) do |f| %>
					<%= f.hidden_field :product_id, value: product.id %>
					<h5><%= product.price %></h5>
					<div class="form-group">
						<%= f.text_field :quantity, value: 1, min: 1, class: 'form-control' %>
					</div>
					<%= f.submit "Add to cart", class: 'btn btn-primary btn-sm' %>
				<% end %>
				</div>
			</div> 
		</div>
	</div>
<% end %>

app/views/layouts/_cart.html.erb
<%= link_to "#{current_order.order_items.size} items in card and price #{current_order.subtotal}", carts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingCart</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to "Home", root_path %></li>
              
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="active cart"><%= render 'layouts/cart' %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
    	<%= yield %>
    </div>
  </body>
</html>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
	alert("Invalid")
<% else %>
	$(".cart").html("<%= escape_javascript(render 'layouts/cart') %>")
<% end %>

app/views/order_items/destroy.js.erb
$(".cart").html("<%= escape_javascript(render 'layouts/cart') %>")
$(".cart_item").html("<%= escape_javascript(render 'carts/cart_item') %>")

app/views/order_items/update.js.erb
$(".cart").html("<%= escape_javascript(render 'layouts/cart') %>")
$(".cart_item").html("<%= escape_javascript(render 'carts/cart_item') %>")

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
	<div class="form-group">
		<%= f.label :name, "Name" %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :price, "Price" %>
		<%= f.number_field :price, value: 1, class: 'form-control', min: 1, :step => "0.01"%>
	</div>

	<%= f.submit "Save", class: 'btn btn-success' %>
<% end %>
  

app/views/products/edit.html.erb
<h3>Update product</h3>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>Products</h1>

<%= link_to "New product", new_product_path %>

<div class="col-md-6 col-md-offset-3">
	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>Price</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			<% @products.each do |product| %>
				<tr>
					<td><%= product.name %></td>
					<td><%= product.price %></td>
					<td>
						<%= link_to "Edit", edit_product_path(product) %>
						<%= link_to "Delete", product_path(product), method: :delete %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/products/new.html.erb
<h3>Create new product</h3>
<%= render 'form' %>